sample_method: sde
convert_scheduler: vp 
scheduler_n: 1.0

text_prompt: bird
guidance_strength: 0.01

#===============================================================================
max_steps: 100
n_particles: 5
max_nfe: 500
#===============================================================================

root_dir: ./results
tag: ${filtering_method}
save_now: True

device: 0
seed: 0

batch_size: 1
block_size: 1
filtering_method: svdd_dps

#===============================================================================
# Trainer settings 
#===============================================================================
disable_debug: False

#===============================================================================
# Dataset 
#===============================================================================
height: 512
width: 512

#===============================================================================
# Time sampler 
#===============================================================================
time_sampler: flux_scheduler
time_schedule: linear
t_max: 1000

#===============================================================================
# Model 
#===============================================================================
model: flux_image
channels: 4096 # [B 4096 64]

#===============================================================================
# Prior
#===============================================================================
prior: flux
guidance_scale: 3.5

diffusion_coefficient: square
diffusion_norm: 3.0

# Only used for "exp" diffusion coefficient
exp_diff_coeff_sigma: 0.1

model_name: "black-forest-labs/FLUX.1-schnell"

#===============================================================================
# Logger
#===============================================================================
logger: self
log_interval: 1

#===============================================================================
# Corrector
#===============================================================================
corrector: particle

reward_weight: 1.0
reward_score: aesthetic
ckpt_root: "./ckpt"