max_nfe: 500
batch_size: 50

reward_score: counting
reward_func: diff
count_reward_model: gdsam
reward_weight: 1.0

#===============================================================================

root_dir: ./results
tag: ${filtering_method}
save_now: True
text_prompt: 

device: 0
seed: 0

block_size: 1
n_particles: 1
minibatch_size: 5
filtering_method: bon

#===============================================================================
# Trainer settings 
#===============================================================================
max_steps: 10
disable_debug: False

#===============================================================================
# Dataset 
#===============================================================================
height: 1024
width: 1024

#===============================================================================
# Time sampler 
#===============================================================================
time_sampler: flux_scheduler
time_schedule: exp
t_max: 1000

#===============================================================================
# Model 
#===============================================================================
model: flux_image
channels: 4096 # [B 4096 64]

#===============================================================================
# Prior
#===============================================================================
prior: flux
guidance_scale: 3.5
sample_method: ode

convert_scheduler: polynomial
scheduler_n: 1

diffusion_coefficient: exp
diffusion_norm: 4.0

model_name: "black-forest-labs/FLUX.1-schnell"

#===============================================================================
# Logger
#===============================================================================
logger: self
log_interval: 1

#===============================================================================
# Corrector
#===============================================================================
corrector: particle