max_nfe: 500
n_particles: 5
batch_size: 2

sample_method: ode
convert_scheduler: vp

reward_score: counting
reward_func: diff
count_reward_model: gdsam
reward_weight: 1.0
scheduler_n: 1

forward_step: 780.0
backward_step: 810.0
ode_seed_t: 120.0
ode_step: 10

#===============================================================================

root_dir: ./results
tag: ${filtering_method}
save_now: True
text_prompt: 

device: 0
seed: 0

block_size: 1
filtering_method: sop

#===============================================================================
# Trainer settings 
#===============================================================================
disable_debug: False

#===============================================================================
# Dataset 
#===============================================================================
height: 1024
width: 1024

#===============================================================================
# Time sampler 
#===============================================================================
time_sampler: flux_scheduler
time_schedule: exp
t_max: 1000

#===============================================================================
# Model 
#===============================================================================
model: flux_image
channels: 4096 # [B 4096 64]

#===============================================================================
# Prior
#===============================================================================
prior: flux
guidance_scale: 3.5


diffusion_coefficient: exp
diffusion_norm: 4.0

model_name: "black-forest-labs/FLUX.1-schnell"

#===============================================================================
# Logger
#===============================================================================
logger: self
log_interval: 1

#===============================================================================
# Corrector
#===============================================================================
corrector: particle

vqa_model: clip-flant5-xxl
vqa_device: 1
vqa_batch_size: 32

image_reward_weight: 0.0