sample_method: 
convert_scheduler: 
scheduler_n: 

text_prompt: 

#===============================================================================
max_steps: 10
n_particles: 50
max_nfe: 500
#===============================================================================

root_dir: ./results
tag: ${filtering_method}
save_now: True

device: 0
seed: 0

batch_size: 1
block_size: 1
filtering_method: svdd

#===============================================================================
# Trainer settings 
#===============================================================================
disable_debug: False

#===============================================================================
# Dataset 
#===============================================================================
height: 1024
width: 1024

#===============================================================================
# Time sampler 
#===============================================================================
time_sampler: flux_scheduler
time_schedule: exp
t_max: 1000

#===============================================================================
# Model 
#===============================================================================
model: flux_image
channels: 4096 # [B 4096 64]

#===============================================================================
# Prior
#===============================================================================
prior: flux
guidance_scale: 3.5

diffusion_coefficient: square
diffusion_norm: 3.0

# Only used for "exp" diffusion coefficient
exp_diff_coeff_sigma: 0.1

model_name: "black-forest-labs/FLUX.1-schnell"

#===============================================================================
# Logger
#===============================================================================
logger: self
log_interval: 1

#===============================================================================
# Corrector
#===============================================================================
corrector: particle

reward_weight: 0.5
reward_score: vqa 

vqa_model: clip-flant5-xxl
vqa_device: 1
vqa_batch_size: 32

image_reward_weight: 0.0


################################################################################################
negative_prompt:
true_cfg_scale: 2.5